trigger:
- main

pr:
- main

jobs:
- job: BuildTestDeploy
  pool:
    vmImage: 'windows-latest' # Use a Windows agent image

  steps:
  - script: echo 'Starting CI/CD pipeline'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install npm packages'

  - script: npm run build
    displayName: 'Build React app'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js for server'

  - script: |
      cd server
      npm install
    displayName: 'Install server dependencies'

  - script: |
      cd server
      npm run test
    displayName: 'Run server tests'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Omar. L Subscription – MPN'
      appType: 'webApp'
      WebAppName: 'mern000'
      packageForWindows: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deployToSlotOrASE: true
      SlotName: 'production' # Change to your desired deployment slot
    displayName: 'Deploy to Azure Web App'

  # Additional steps for setting up environment variables, configuring Azure services, etc.
